neoForge {
    // Specify NeoForge version
    version = libs.versions.neoForge.get()

    parchment {
        minecraftVersion = libs.versions.minecraft.get()
        mappingsVersion = libs.versions.parchment.get()
    }

    // Access Transformers are auto-detected at src/main/resources/META-INF/accesstransformer.cfg

    mods {
        // define mod <-> source bindings
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        client {
            client()
            sourceSet = sourceSets.main
            ideName = "Client"

            gameDirectory.set(file("runs/client"))
            systemProperty('neoforge.enabledGameTestNamespaces', project.mod_id)
        }

        client2 {
            client()
            sourceSet = sourceSets.main
            ideName = "Client (2)"

            programArguments.addAll('--username', 'YoungOnion')
            gameDirectory.set(file("runs/client2"))
            systemProperty('neoforge.enabledGameTestNamespaces', project.mod_id)
        }

        server {
            server()
            sourceSet = sourceSets.main
            ideName = "Server"

            gameDirectory.set(file("runs/server"))
            programArgument '--nogui'
            systemProperty('neoforge.enabledGameTestNamespaces', project.mod_id)
        }

        data {
            data()
            sourceSet = sourceSets.main
            ideName = "Data Generation"

            gameDirectory.set(file("runs/data"))
            programArguments.addAll('--mod', project.mod_id)
            programArguments.addAll('--all')
            programArguments.addAll('--output', file('src/generated/resources/').getAbsolutePath())
            programArguments.addAll('--existing', file('src/main/resources/').getAbsolutePath())
            programArguments.addAll('--existing-mod', 'gtceu')
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.INFO
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
