plugins {
    id "idea"
    id "maven-publish"
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'com.diffplug.spotless' version '7.0.2'
}

def generatedResources = file("src/generated")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = 'GTCEu Maven'
        url = 'https://maven.gtceu.com'
        content {
            includeGroup 'com.gregtechceu.gtceu'
        }
    }
    maven { // Curse Forge File
        url = "https://cursemaven.com/"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { // Ad Astra
        url = "https://maven.teamresourceful.com/repository/maven-public/"
    }
    maven {
        name = "Modmaven"
        url = "https://modmaven.dev/"
        content {
            includeGroup 'appeng'
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/releases/"
    }
    maven {
        name = 'FirstDarkDev'
        url = 'https://maven.firstdarkdev.xyz/snapshots/'
    }
    maven { // saps.dev Maven (KubeJS and Rhino)
        url "https://maven.saps.dev/releases/"
        content {
            includeGroup "dev.latvian.mods"
        }
    }
    maven { // Registrate
        url = "https://maven.tterrag.com/"
        content {
            // need to be specific here due to version overlaps
            includeGroup("com.jozufozu.flywheel")
            includeGroup("com.tterrag.registrate")
            includeGroup("com.simibubi.create")
        }
    }
    maven { // Patchouli, JEI
        name = "BlameJared"
        url = "https://maven.blamejared.com/"
    }
    maven { // Curios
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        url = "https://maven.shadowsoffire.dev/releases"
    }
    maven {
        name = 'GeckoLib'
        url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
    }
    maven {
        name = "tterrag maven"
        url = "https://maven.tterrag.com/"
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url = "https://maven.architectury.dev"
    }
    maven {
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }
}

version = mod_version
group = maven_group

base { archivesName = archives_base_name }
java { sourceCompatibility = targetCompatibility = JavaVersion.VERSION_17 }
sourceSets.main.resources { srcDir 'src/generated/resources' }

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods { "${mod_id}" { source sourceSets.main } }
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
        }
        client { property 'forge.enabledGameTestNamespaces', mod_id }
        server { property 'forge.enabledGameTestNamespaces', mod_id; args '--nogui' }
        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources'), '--existing', file('src/main/resources/'), '--existing-mod', 'gtceu', '--client', '--server'
        }
    }
}

mixin {
    // MixinGradle Settings
    add sourceSets.main, 'com.ghostipedia.cosmiccore.mixin'
    config 'cosmiccore.mixins.json'
}

apply from: "$rootDir/gradle/scripts/spotless.gradle"

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor' // Apply Mixin AP

    // JEI, EMI, Jade
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    runtimeOnly fg.deobf("dev.emi:emi-forge:${emi_version}+${minecraft_version}")
    runtimeOnly fg.deobf("maven.modrinth:jade:${jade_version}+forge")


    // GregTech and dependencies
    implementation fg.deobf("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gtceu_version}:slim") { transitive = false }
    implementation fg.deobf("com.lowdragmc.ldlib:ldlib-forge-${minecraft_version}:${ldlib_version}") { transitive = false }
    implementation fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")
    implementation fg.deobf("dev.latvian.mods:kubejs-forge:${kubejs_version}")
    implementation fg.deobf("dev.latvian.mods:rhino-forge:${rhino_version}")
    runtimeOnly fg.deobf("dev.toma.configuration:configuration-forge-${minecraft_version}:${configuration_version}")
    runtimeOnly fg.deobf("dev.architectury:architectury-forge:${architectury_version}")

    implementation fg.deobf("appeng:appliedenergistics2-forge:15.2.13")
    implementation fg.deobf("curse.maven:modern-ae2-additions-1028068:5826205") { transitive = false }
    implementation fg.deobf("curse.maven:legendary-survival-overhaul-840254:5921074") { transitive = false }

    // Ad Astra
    runtimeOnly fg.deobf("com.teamresourceful:yabn:1.0.3") // Cause architectury is kinda dumb with some java libs
    runtimeOnly fg.deobf("com.teamresourceful:bytecodecs:1.0.2") // Cause architectury is kinda dumb with some java libs
    implementation fg.deobf("com.teamresourceful.resourcefullib:resourcefullib-forge-${project.minecraft_version}:${project.resourcefullib_version}")
    implementation fg.deobf("com.teamresourceful.resourcefulconfig:resourcefulconfig-forge-${project.minecraft_version}:${project.resourcefulconfig_version}")
    implementation fg.deobf("earth.terrarium.botarium:botarium-forge-${project.minecraft_version}:${project.botarium_version}")
    implementation fg.deobf("earth.terrarium.adastra:ad_astra-forge-${project.minecraft_version}:${ad_astra_version}") {transitive false} // issue with create mod so not transitive

    implementation fg.deobf("maven.modrinth:blood-magic:${minecraft_version}-${blood_magic_version}")

    implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.20.1:4.2.2')
    compileOnly fg.deobf("com.jozufozu.flywheel:flywheel-forge-1.20.1:0.6.10-7")
    compileOnly fg.deobf("curse.maven:create-328085:4762216")
    compileOnly fg.deobf("curse.maven:new-thin-air-878379:4848005")
    implementation fg.deobf("curse.maven:puzzles-lib-495476:4924184")

    implementation fg.deobf("dev.shadowsoffire:Apotheosis:${project.minecraft_version}-7.4.2")
    implementation fg.deobf("dev.shadowsoffire:Placebo:${project.minecraft_version}-8.6.2")
    implementation fg.deobf("dev.shadowsoffire:ApothicAttributes:${project.minecraft_version}-1.3.5")

    runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:${project.minecraft_version}-${project.patchouli_version}-FORGE")
    implementation fg.deobf("top.theillusivec4.curios:curios-forge:${project.curios_version}+${project.minecraft_version}")

    implementation fg.deobf("maven.modrinth:embeddium:0.3.31+mc1.20.1")
    implementation fg.deobf("maven.modrinth:oculus:1.20.1-1.7.0")
    runtimeOnly fg.deobf("org.anarres:jcpp:1.4.14") // oculus needs this apparently??? idk

    // FTB
    implementation fg.deobf("curse.maven:ftb-teams-forge-404468:${project.ftb_team}")
    implementation fg.deobf("curse.maven:ftb-teams-forge-404465:${project.ftb_lib}")

    // Mixin Extras
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${project.mixinextras_version}"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${project.mixinextras_version}")) { jarJar.ranged(it, "[${project.mixinextras_version},)") }
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    // lombok
    compileOnly 'org.projectlombok:lombok:1.18.24'
    annotationProcessor 'org.projectlombok:lombok:1.18.24'
}

tasks.named('processResources', ProcessResources).configure {
    var properties = [
            "mod_license": mod_license,
            "mod_id": mod_id,
            "version": version,
            "mod_name": mod_name,
            "mod_url": mod_url,
            "mod_author": mod_author,
            "forge_version": forge_version.split("\\.")[0], // only specify major version of forge
            "minecraft_version": minecraft_version,
            "gtceu_version": gtceu_version,
    ]
    inputs.properties(properties)

    filesMatching("META-INF/mods.toml") {
        expand properties + [project: project]
    }
}

tasks.named('jar', Jar).configure { finalizedBy 'reobfJar' }
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    options.encoding = "UTF-8"
    options.release.set(17)
}