org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true

# Mod Properties
mod_id = cosmiccore
mod_name = Cosmic Core
mod_version = 0.21.0
mod_description = The Core of Cosmic Frontiers!
mod_authors = Ghostipedia
mod_license = Code : LGPL-3.0 , Assets: Refer to Github.
mod_url = https://github.com/Frontiers-PackForge/CosmicCore/
mod_issue_tracker = https://github.com/Frontiers-PackForge/CosmicCore/issues/
maven_group = com.ghostipedia.frontiers
