modLoader = "javafml"
loaderVersion = "[${forge_version},)"
license = "${mod_license}"


[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"
displayURL = "${mod_url}"


[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ldlib"
mandatory = false
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="gtceu"
mandatory=true
versionRange="[1.2.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "kubejs"
mandatory = false
versionRange = "[${kjs_version},)"
ordering = "AFTER"
side = "BOTH"