package com.ghostipedia.cosmiccore.common.machine.multiblock.multi.modular;

import com.ghostipedia.cosmiccore.CosmicCore;
import com.ghostipedia.cosmiccore.api.block.IMultiblockProvider;
import com.ghostipedia.cosmiccore.api.block.IMultiblockReciever;
import com.ghostipedia.cosmiccore.common.data.CosmicBlocks;
import com.ghostipedia.cosmiccore.common.data.CosmicModularMachines;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.GTValues;
import com.gregtechceu.gtceu.api.blockentity.BlockEntityCreationInfo;
import com.gregtechceu.gtceu.api.capability.IEnergyContainer;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.misc.EnergyContainerList;
import com.gregtechceu.gtceu.api.multiblock.pattern.MultiblockPatternBuilder;
import com.gregtechceu.gtceu.api.multiblock.Predicates;
import com.gregtechceu.gtceu.api.recipe.OverclockingLogic;
import com.gregtechceu.gtceu.common.data.GTRecipeModifiers;
import com.gregtechceu.gtceu.common.data.GTRecipeTypes;

import com.lowdragmc.lowdraglib.gui.texture.GuiTextureGroup;
import com.lowdragmc.lowdraglib.gui.texture.TextTexture;
import com.lowdragmc.lowdraglib.gui.widget.*;

import net.minecraft.network.chat.Component;

import lombok.Getter;

import java.util.Collection;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

import javax.annotation.Nullable;

import static com.ghostipedia.cosmiccore.api.registries.CosmicRegistration.REGISTRATE;
import static com.gregtechceu.gtceu.api.multiblock.Predicates.*;

public class StarLadderOld extends WorkableElectricMultiblockMachine implements IMultiblockProvider {

    @Nullable
    protected EnergyContainerList inputEnergyContainers;
    // assuming a collection is just like a map, but it lost the actual mapping
    @Getter
    protected boolean isFuelable;
    private final Collection<IMultiblockReciever> starLadderReceivers = ConcurrentHashMap.newKeySet();

    public StarLadderOld(BlockEntityCreationInfo holder) {
        super(holder);
    }

    protected int tetherTier = 0;

    @Override
    public int getModulatorTier() {
        return 0;
    }

    private int getMaxModules() {
        if (this.tetherTier == 1) return 6;
        if (this.tetherTier == 2) return 12;
        if (this.tetherTier == 3) return 16;
        return 4;
    }

    @Override
    public IEnergyContainer getEnergyContainersForModules() {
        return this.inputEnergyContainers;
    }

    @Override
    public boolean amIAModule(IMultiblockProvider receiver) {
        return this.starLadderReceivers.contains(receiver);
    }

    @Override
    public void formStructure(@org.jetbrains.annotations.NotNull String substructureName) {
        super.formStructure(substructureName);
    }

    @Override
    public void invalidateStructure(String substructureName) {
        super.invalidateStructure(substructureName);
        this.starLadderReceivers.forEach(IMultiblockReciever::sendWorkingDisabled);
        this.starLadderReceivers.forEach(s -> s.setModularMultiBlock(null));
    }

    public void isfuelable(boolean fuelable) {
        this.isFuelable = fuelable;
    }
    // New Code ft. Ghost what the HELL are you doing...
    // @NotNull
    // protected static TraceabilityPredicate starLadderModulesOld() {
    // return new TraceabilityPredicate(MultiblockState -> {
    // var blockState = MultiblockState.getBlockState();
    // Block block = blockState.getBlock();
    // MetaMachine metaMachine = MetaMachine.getMachine(level, pos);
    // if (blockState.is(STAR_LADDER_BLOCKS)) {
    // if(block == CosmicBlocks.STAR_LADDER_CASING.get()) return true;
    // }
    // if(metaMachine == null) return false;
    // if (metaMachine instanceof IMultiblockProvider) return false;
    // if (!(metaMachine instanceof IMultiblockReciever starLadderReceiver)) return false;
    // if(starLadderReceiver.getModularMultiBlock() != this){
    // starLadderReceiver.setModularMultiBlock(this);
    // this.starLadderReceivers.add(starLadderReceiver);
    // }
    // return true;
    // }, () -> CosmicCoreAPI.STARLADDER_CASINGS.entrySet().stream()
    // // sort to make autogenerated jei previews not pick random coils each game load
    // .map(coil -> BlockInfo.fromBlockState(coil.getValue().get().defaultBlockState()))
    // .toArray(BlockInfo[]::new))
    // .addTooltips(Component.translatable("gtceu.multiblock.pattern.error.coils"));
    // }

    public static final MultiblockMachineDefinition STAR_LADDER = REGISTRATE
            .multiblock("star_ladder", StarLadderOld::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType(GTRecipeTypes.DUMMY_RECIPES)
            .recipeModifier(GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK_SUBTICK))
            .appearanceBlock(CosmicBlocks.CYCLOZINE_CHEMICALLY_REPELLING_CASING)
            .pattern(definition -> MultiblockPatternBuilder.start()
                    .slice("A   A", "A   A", "A   A", "A   A")
                    .slice("AAAAA", "A B A", "Q   Q", "A   A")
                    .where(' ', any())
                    .where('B', controller(blocks(definition.getBlock())))
                    .where('A', blocks(CosmicBlocks.CYCLOZINE_CHEMICALLY_REPELLING_CASING.get())
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                            .or(Predicates.abilities(PartAbility.INPUT_LASER).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.OUTPUT_LASER).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16)))
                    .where('Q', blocks(CosmicModularMachines.STAR_LADDER_TEST_MODULE[GTValues.ZPM].get()))
                    // blocks(Arrays.stream(CosmicModularMachines.STAR_LADDER_TEST_MODULE).filter(Objects::nonNull).map(Supplier::get).toArray(IMachineBlock[]::new))
                    .build())
            .workableCasingModel(CosmicCore.id("block/casings/solid/vomahine_certified_chemically_resistant_casing"),
                    GTCEu.id("block/multiblock/fusion_reactor"))
            .tooltips(Component.translatable("cosmiccore.multiblock.iris.tooltip.0"),
                    Component.translatable("cosmiccore.multiblock.iris.tooltip.1"),
                    Component.translatable("cosmiccore.multiblock.iris.tooltip.2"),
                    Component.translatable("cosmiccore.multiblock.iris.tooltip.3"))
            .register();

    // TODO(8.0.0 MUI2): the LDLib createUIWidget/addDisplayText surface (star-ladder tier readout + send-orbit
    //  button) was removed in GTCEu 8.0.0. Rebuild on MUI2 when the StarLadder UI is ported. Logic preserved.

    public static void init() {}
}
