package com.ghostipedia.cosmiccore.common.machine.multiblock.multi;

import com.ghostipedia.cosmiccore.CosmicCore;
import com.ghostipedia.cosmiccore.gtbridge.CosmicRecipeTypes;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.multiblock.pattern.MultiblockPatternBuilder;
import com.gregtechceu.gtceu.api.multiblock.util.RelativeDirection;
import com.gregtechceu.gtceu.api.recipe.OverclockingLogic;
import com.gregtechceu.gtceu.common.data.GTBlocks;
import com.gregtechceu.gtceu.common.data.GTMaterials;
import com.gregtechceu.gtceu.common.data.GTRecipeModifiers;

import static com.ghostipedia.cosmiccore.api.registries.CosmicRegistration.REGISTRATE;
import static com.ghostipedia.cosmiccore.common.data.CosmicBlocks.*;
import static com.gregtechceu.gtceu.api.multiblock.Predicates.*;

public class ComponentAssemblyLine {

    public final static MultiblockMachineDefinition COMPONENT_ASSEMBLY_LINE = REGISTRATE
            .multiblock("component_assembly_line",
                    WorkableElectricMultiblockMachine::new)
            .langValue("§aComponent Assembly Line")
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType(CosmicRecipeTypes.COMPONENT_ASSEMBLY_LINE)
            .appearanceBlock(BICHROMAL_NEVRAMITE_CASING)
            .partAppearance((controller, part, side) -> BICHROMAL_NEVRAMITE_CASING.getDefaultState())
            .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH,
                    GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK_SUBTICK),
                    GTRecipeModifiers.BATCH_MODE)
            // spotless:off
            .pattern(definition -> MultiblockPatternBuilder.start(RelativeDirection.LEFT,RelativeDirection.UP,RelativeDirection.FRONT)
                    .slice("  AAAAA     IIIIIII     AAAAA  ", "  AAAAA     IIIIIII     AAAAA  ", "  AAAAA     IIIIIII     AAAAA  ", "  AAAAA     IIIIIII     AAAAA  ", "  AAAAA     IIIIIII     AAAAA  ", "    A A      IIIII      A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A AA               AA A    ", "    A AA               AA A    ", "  AAAAAAAA           AAAAAAAA  ", "  AAAAAAAAAAA     AAAAAAAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAA                 AAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAAFFFFFCKKKKKCFFFFFAAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F         H         F     ", "  ACCCA      HH         ACCCA  ", "   D D      H            D D   ", "   E E     H             E E   ", "   D D     H             D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     B                   B     ", "     B                   B     ", "     B                   B     ", "     B        I I        B     ", "     B        III        B     ", "     B         I         B     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAAFFFFFCKKKKKCFFFFFAAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F         H         F     ", "  ACCCA      HH         ACCCA  ", "   D D      H            D D   ", "   E E     H             E E   ", "   D D     H             D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAA      CCCCC      AAAAA  ", "  AAAAA     CKKKKKC     AAAAA  ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAA                 AAAAA  ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "    FFFFFFFFFFFFFFFFFFFFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDD               DDDBF   ", "    FFFFGGGGGGGGGGGGGGGFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDD                 DDBF   ", "    FFFGGGGGGGGGGGGGGGGGFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("AAA                         AAA", "A A FF                   FF A A", "A AFBDDDDDDDDDDDDDDDDDDDDDBFA A", "A AF         CCCCC         FA A", "A A         CKKKKKC         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A AF                       FA A", "A AFBDD                 DDBFA A", "A A FFFGGGGGGGGGGGGGGGGGFFF A A", "A A AAA                 AAA A A", "A AAA A                 A AAA A", "A     A                 A     A", "AAAAAAA                 AAAAAAA")
                    .slice("AAA                         AAA", " B  FF                   FF  B ", " B FBDDDDDDDDDDDDDDDDDDDDDBF B ", " B F         CCCCC         F B ", " B          CKKKKKC          B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B F                       F B ", " B FBDD                 DDBF B ", " B  FFFGGGGGGGGGGGGGGGGGFFF  B ", " B  AAA                 AAA  B ", " B   B                   B   B ", " BBBBB                   BBBBB ", "AAA   A                 A   AAA")
                    .slice("AAA                         AAA", "A A FF                   FF A A", "A AFBDDDDDDDDDDDDDDDDDDDDDBFA A", "A AF         CCCCC         FA A", "A A         CKKKKKC         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A AF                       FA A", "A AFBDD                 DDBFA A", "A A FFFGGGGGGGGGGGGGGGGGFFF A A", "A A AAA                 AAA A A", "A AAA A                 A AAA A", "A     A                 A     A", "AAAAAAA                 AAAAAAA")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDD                 DDBF   ", "    FFFGGGGGGGGGGGGGGGGGFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDD               DDDBF   ", "    FFFFGGGGGGGGGGGGGGGFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "    FFFFFFFFFFFFFFFFFFFFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAA      CCCCC      AAAAA  ", "  AAAAA     CKKKKKC     AAAAA  ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAA                 AAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAAFFFFFCKKKKKCFFFFFAAAAA  ", "     F                   F     ", "     F                   F     ", "     F             H     F     ", "     F              H    F     ", "     F              H    F     ", "     F              H    F     ", "  ACCCA              H  ACCCA  ", "   D D               H   D D   ", "   E E               H   E E   ", "   D D               H   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     B                   B     ", "     B           II      B     ", "     B            II     B     ", "     B           II      B     ", "     B                   B     ", "     B                   B     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAAFFFFFCKKKKKCFFFFFAAAAA  ", "     F                   F     ", "     F                   F     ", "     F             H     F     ", "     F              H    F     ", "     F              H    F     ", "     F              H    F     ", "  ACCCA              H  ACCCA  ", "   D D               H   D D   ", "   E E               H   E E   ", "   D D               H   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAA      CCCCC      AAAAA  ", "  AAAAA     CKKKKKC     AAAAA  ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAA                 AAAAA  ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "    FFFFFFFFFFFFFFFFFFFFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDD               DDDBF   ", "    FFFFGGGGGGGGGGGGGGGFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDD                 DDBF   ", "    FFFGGGGGGGGGGGGGGGGGFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("AAA                         AAA", "A A FF                   FF A A", "A AFBDDDDDDDDDDDDDDDDDDDDDBFA A", "A AF         CCCCC         FA A", "A A         CKKKKKC         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A AF                       FA A", "A AFBDD                 DDBFA A", "A A FFFGGGGGGGGGGGGGGGGGFFF A A", "A A AAA                 AAA A A", "A AAA A                 A AAA A", "A     A                 A     A", "AAAAAAA                 AAAAAAA")
                    .slice("AAA                         AAA", " B  FF                   FF  B ", " B FBDDDDDDDDDDDDDDDDDDDDDBF B ", " B F         CCCCC         F B ", " B          CKKKKKC          B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B F                       F B ", " B FBDD                 DDBF B ", " B  FFFGGGGGGGGGGGGGGGGGFFF  B ", " B  AAA                 AAA  B ", " B   B                   B   B ", " BBBBB                   BBBBB ", "AAA   A                 A   AAA")
                    .slice("AAA                         AAA", "A A FF                   FF A A", "A AFBDDDDDDDDDDDDDDDDDDDDDBFA A", "A AF         CCCCC         FA A", "A A         CKKKKKC         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A AF                       FA A", "A AFBDD                 DDBFA A", "A A FFFGGGGGGGGGGGGGGGGGFFF A A", "A A AAA                 AAA A A", "A AAA A                 A AAA A", "A     A                 A     A", "AAAAAAA                 AAAAAAA")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDD                 DDBF   ", "    FFFGGGGGGGGGGGGGGGGGFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDD               DDDBF   ", "    FFFFGGGGGGGGGGGGGGGFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "    FFFFFFFFFFFFFFFFFFFFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAA      CCCCC      AAAAA  ", "  AAAAA     CKKKKKC     AAAAA  ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAA                 AAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAAFFFFFCKKKKKCFFFFFAAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F         H         F     ", "     F        HIH        F     ", "     F         H         F     ", "  ACCCA      HH         ACCCA  ", "   D D      H            D D   ", "   E E      H            E E   ", "   D D     H             D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     B                   B     ", "     B                   B     ", "     B         L         B     ", "     B         I         B     ", "     B         I         B     ", "     B                   B     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAAFFFFFCKKKKKCFFFFFAAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F         H         F     ", "     F        HIH        F     ", "     F         H         F     ", "  ACCCA      HH         ACCCA  ", "   D D      H            D D   ", "   E E      H            E E   ", "   D D     H             D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAA      CCCCC      AAAAA  ", "  AAAAA     CKKKKKC     AAAAA  ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAA                 AAAAA  ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "    FFFFFFFFFFFFFFFFFFFFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDD               DDDBF   ", "    FFFFGGGGGGGGGGGGGGGFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDD                 DDBF   ", "    FFFGGGGGGGGGGGGGGGGGFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("AAA                         AAA", "A A FF                   FF A A", "A AFBDDDDDDDDDDDDDDDDDDDDDBFA A", "A AF         CCCCC         FA A", "A A         CKKKKKC         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A AF                       FA A", "A AFBDD                 DDBFA A", "A A FFFGGGGGGGGGGGGGGGGGFFF A A", "A A AAA                 AAA A A", "A AAA A                 A AAA A", "A     A                 A     A", "AAAAAAA                 AAAAAAA")
                    .slice("AAA                         AAA", " B  FF                   FF  B ", " B FBDDDDDDDDDDDDDDDDDDDDDBF B ", " B F         CCCCC         F B ", " B          CKKKKKC          B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B                           B ", " B F                       F B ", " B FBDD                 DDBF B ", " B  FFFGGGGGGGGGGGGGGGGGFFF  B ", " B  AAA                 AAA  B ", " B   B                   B   B ", " BBBBB                   BBBBB ", "AAA   A                 A   AAA")
                    .slice("AAA                         AAA", "A A FF                   FF A A", "A AFBDDDDDDDDDDDDDDDDDDDDDBFA A", "A AF         CCCCC         FA A", "A A         CKKKKKC         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A A                         A A", "A AF                       FA A", "A AFBDD                 DDBFA A", "A A FFFGGGGGGGGGGGGGGGGGFFF A A", "A A AAA                 AAA A A", "A AAA A                 A AAA A", "A     A                 A     A", "AAAAAAA                 AAAAAAA")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDD                 DDBF   ", "    FFFGGGGGGGGGGGGGGGGGFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDD               DDDBF   ", "    FFFFGGGGGGGGGGGGGGGFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("                               ", "    FF                   FF    ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "   F         CCCCC         F   ", "            CKKKKKC            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "   F                       F   ", "   FBDDDDDDDDDDDDDDDDDDDDDBF   ", "    FFFFFFFFFFFFFFFFFFFFFFF    ", "                               ", "                               ", "                               ", "                               ")
                    .slice("  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAA      CCCCC      AAAAA  ", "  AAAAA     CKKKKKC     AAAAA  ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "  AAAAA                 AAAAA  ", "  AAAAA                 AAAAA  ", "  AAAAADDDDDDDDDDDDDDDDDAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAA                 AAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAAFFFFFCKKKKKCFFFFFAAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F         I         F     ", "     F         H         F     ", "     F         H         F     ", "  ACCCA        H        ACCCA  ", "   D D          H        D D   ", "   E E          H        E E   ", "   D D          H        D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     B                   B     ", "     B                   B     ", "     B         L         B     ", "     B        LIL        B     ", "     B         L         B     ", "     B                   B     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAAFFFFFCKKKKKCFFFFFAAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F         I         F     ", "     F         H         F     ", "     F         H         F     ", "  ACCCA        H        ACCCA  ", "   D D        H          D D   ", "   E E        H          E E   ", "   D D        H          D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  ACCCA                 ACCCA  ", "   D DAAAAAAAAAAAAAAAAAAAD D   ", "   E E                   E E   ", "   D D       CCCCC       D D   ", "  AAAAA     CKKKKKC     AAAAA  ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "     F                   F     ", "  ACCCA                 ACCCA  ", "   D D                   D D   ", "   E E                   E E   ", "   D D                   D D   ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "                               ", "                               ", "                               ")
                    .slice("  AAAAA     IIIIIII     AAAAA  ", "  AAAAA     IIIIIII     AAAAA  ", "  AAAAA     IIIIIII     AAAAA  ", "  AAAAA     IIIIIII     AAAAA  ", "  AAAAA     IIIIIII     AAAAA  ", "    A A      IIIII      A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A A                 A A    ", "    A AA               AA A    ", "    A AA               AA A    ", "  AAAAAAAA           AAAAAAAA  ", "  AAAAAAAAAAA     AAAAAAAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAAAAAAAAAAAAAAAAAAAAAAAA  ", "  AAAAA                 AAAAA  ", "                               ", "                               ", "                               ")
                    .slice("             JJJJJ             ", "             JJJJJ             ", "             JJQJJ             ", "             JJJJJ             ", "              JJJ              ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ")
                    .where(' ', any())
                    .where('Q', controller(blocks(definition.getBlock())))
                    .where('A', blocks(BICHROMAL_NEVRAMITE_CASING.get()))
                    .where('B', blocks(ULTRA_POWERED_CASING.get()))
                    .where('C', blocks(HIGHLY_CONDUCTIVE_FISSION_CASING.get()))
                    .where('D', blocks(GTBlocks.COMPUTER_CASING.get()))
                    .where('E', blocks(GTBlocks.HIGH_POWER_CASING.get()))
                    .where('F', blocks(CYCLOZINE_CHEMICALLY_REPELLING_CASING.get()))
                    .where('G', blocks(ZBLAN_REINFORCED_GLASS.get()))
                    .where('H', frames(GTMaterials.Neutronium))
                    .where('I', blocks(TRITANIUM_LINED_HEAVY_NEUTRONIUM_CASING.get()))
                    .where('J', blocks(BICHROMAL_NEVRAMITE_CASING.get())
                            .or(autoAbilities(CosmicRecipeTypes.MANA_DIGITIZER,CosmicRecipeTypes.MANA_FLUIDIZER))
                            .or(abilities(PartAbility.INPUT_ENERGY).setExactLimit(1))
                            .or(abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))
                            .or(abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
                    .where('K', blocks(HIGHLY_CONDUCTIVE_FISSION_CASING.get()))
                    .where('L', blocks(GEARBOX_PTHANTERUM.get()))
                    .build())
            // spotless:on
            .workableCasingModel(CosmicCore.id("block/casings/solid/bichromal_nevramite_casing"),
                    GTCEu.id("block/multiblock/power_substation"))
            .register();

    public static void init() {}
}
