package com.ghostipedia.cosmiccore.common.machine.multiblock.multi;

import com.ghostipedia.cosmiccore.CosmicCore;
import com.ghostipedia.cosmiccore.api.machine.multiblock.IrisMultiblockMachine;
import com.ghostipedia.cosmiccore.client.renderer.machine.CosmicDynamicRenderHelpers;
import com.ghostipedia.cosmiccore.common.data.CosmicBlocks;
import com.ghostipedia.cosmiccore.gtbridge.CosmicRecipeTypes;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.multiblock.pattern.MultiblockPatternBuilder;
import com.gregtechceu.gtceu.api.multiblock.Predicates;
import com.gregtechceu.gtceu.api.recipe.OverclockingLogic;
import com.gregtechceu.gtceu.common.data.GTRecipeModifiers;

import net.minecraft.network.chat.Component;

import static com.ghostipedia.cosmiccore.api.registries.CosmicRegistration.REGISTRATE;
import static com.ghostipedia.cosmiccore.common.data.CosmicBlocks.*;
import static com.gregtechceu.gtceu.api.multiblock.Predicates.*;
import static com.gregtechceu.gtceu.api.multiblock.Predicates.blocks;
import static com.gregtechceu.gtceu.common.data.GCYMBlocks.CASING_ATOMIC;
import static com.gregtechceu.gtceu.common.data.GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING;
import static com.gregtechceu.gtceu.common.data.models.GTMachineModels.createWorkableCasingMachineModel;

public class StellarStarBallast {

    public final static MultiblockMachineDefinition STAR_BALLAST = REGISTRATE.multiblock("star_ballast",
            IrisMultiblockMachine::new)
            .rotationState(RotationState.Y_AXIS)
            .recipeType(CosmicRecipeTypes.VOMAHINE_CORE_DRILL)
            .recipeModifier(GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK_SUBTICK))
            .appearanceBlock(CosmicBlocks.CYCLOZINE_CHEMICALLY_REPELLING_CASING)
            .pattern(definition -> MultiblockPatternBuilder.start()
                    .slice("                           AAAAA                           ",
                            "                        BBBBBBBBBBB                        ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                        BBBBBBBBBBB                        ",
                            "                           AAAAA                           ")
                    .slice("                          AAAAAAA                          ",
                            "                    BBBBBBBBBBBBBBBBBBB                    ",
                            "                        CBBDDDDDBBC                        ",
                            "                         BB     BB                         ",
                            "                         BB     BB                         ",
                            "                        BBB     BBB                        ",
                            "                         BB     BB                         ",
                            "                         BB     BB                         ",
                            "                        CBBDDDDDBBC                        ",
                            "                    BBBBBBBBBBBBBBBBBBB                    ",
                            "                          AAAAAAA                          ")
                    .slice("                          AADDDAA                          ",
                            "                  BBBBBBBBBBBBBBBBBBBBBBB                  ",
                            "                     CCCAAAAAAAAAAACCC                     ",
                            "                        AAAAAAAAAAA                        ",
                            "                        AAAAAAAAAAA                        ",
                            "                     BBBAAAAAAAAAAABBB                     ",
                            "                        AAAAAAAAAAA                        ",
                            "                        AAAAAAAAAAA                        ",
                            "                     CCCAAAAAAAAAAACCC                     ",
                            "                  BBBBBBBBBBBBBBBBBBBBBBB                  ",
                            "                          AADDDAA                          ")
                    .slice("                          AADFDAA                          ",
                            "                BBBBBBBBGGGGGGGGGGGBBBBBBBB                ",
                            "                  CCCAAAAAAAAAAAAAAAAACCC                  ",
                            "                     AAAAAAAAAAAAAAAAA                     ",
                            "                     AAAAAAACCCAAAAAAA                     ",
                            "                  BBBAAAAAAACCCAAAAAAABBB                  ",
                            "                     AAAAAAACCCAAAAAAA                     ",
                            "                     AAAAAAAAAAAAAAAAA                     ",
                            "                  CCCAAAAAAAAAAAAAAAAACCC                  ",
                            "                BBBBBBBBGGGGGGGGGGGBBBBBBBB                ",
                            "                          AADFDAA                          ")
                    .slice("                          AADDDAA                          ",
                            "              BBBBBBBGGGBBBBBBBBBBBGGGBBBBBBB              ",
                            "                CCAAAAAAAAAAAAAAAAAAAAAAACC                ",
                            "                  AAAAAAAAAAAAAAAAAAAAAAA                  ",
                            "                  AAAAAAAAAA C AAAAAAAAAA                  ",
                            "                BBAAAAAAAAAACCCAAAAAAAAAABB                ",
                            "                  AAAAAAAAAA C AAAAAAAAAA                  ",
                            "                  AAAAAAAAAAAAAAAAAAAAAAA                  ",
                            "                CCAAAAAAAAAAAAAAAAAAAAAAACC                ",
                            "              BBBBBBBGGGBBBBBBBBBBBGGGBBBBBBB              ",
                            "                          AADDDAA                          ")
                    .slice("                          AAAAAAA                          ",
                            "            BBBBBBGGGBBBBBBBBBBBBBBBBBGGGBBBBBB            ",
                            "              CCAAAAAAAACBBDDDDDBBCAAAAAAAACC              ",
                            "                AAAAAAAA BB     BB AAAAAAAA                ",
                            "                AAAAAAAA BB  C  BB AAAAAAAA                ",
                            "              BBAAAAAAAABBB CCC BBBAAAAAAAABB              ",
                            "                AAAAAAAA BB  C  BB AAAAAAAA                ",
                            "                AAAAAAAA BB     BB AAAAAAAA                ",
                            "              CCAAAAAAAACBBDDDDDBBCAAAAAAAACC              ",
                            "            BBBBBBGGGBBBBBBBBBBBBBBBBBGGGBBBBBB            ",
                            "                          AAAAAAA                          ")
                    .slice("                           AAAAA                           ",
                            "           BBBBBGGBBBBBBBBBBBBBBBBBBBBBBBGGBBBBB           ",
                            "             CAAAAAAACCC           CCCAAAAAAAC             ",
                            "              AAAAAAA                 AAAAAAA              ",
                            "              AAAAAAA        C        AAAAAAA              ",
                            "             BAAAAAAABBB    CCC    BBBAAAAAAAB             ",
                            "              AAAAAAA        C        AAAAAAA              ",
                            "              AAAAAAA                 AAAAAAA              ",
                            "             CAAAAAAACCC           CCCAAAAAAAC             ",
                            "           BBBBBGGBBBBBBBBBBBBBBBBBBBBBBBGGBBBBB           ",
                            "                           AAAAA                           ")
                    .slice("                                                           ",
                            "          BBBBGGBBBBBBBBB         BBBBBBBBBGGBBBB          ",
                            "            CAAAAACCC                 CCCAAAAAC            ",
                            "             AAAAA                       AAAAA             ",
                            "             AAAAA                       AAAAA             ",
                            "            BAAAAABBB        C        BBBAAAAAB            ",
                            "             AAAAA                       AAAAA             ",
                            "             AAAAA                       AAAAA             ",
                            "            CAAAAACCC                 CCCAAAAAC            ",
                            "          BBBBGGBBBBBBBBB         BBBBBBBBBGGBBBB          ",
                            "                                                           ")
                    .slice("                                                           ",
                            "         BBBBGBBBBBBB                 BBBBBBBGBBBB         ",
                            "           CAAAAAC                       CAAAAAC           ",
                            "            AAAAA                         AAAAA            ",
                            "            AAAAA                         AAAAA            ",
                            "           BAAAAAB           C           BAAAAAB           ",
                            "            AAAAA                         AAAAA            ",
                            "            AAAAA                         AAAAA            ",
                            "           CAAAAAC                       CAAAAAC           ",
                            "         BBBBGBBBBBBB                 BBBBBBBGBBBB         ",
                            "                                                           ")
                    .slice("                                                           ",
                            "        BBBBGBBBBBB                     BBBBBBGBBBB        ",
                            "          CAAAACC                         CCAAAAC          ",
                            "           AAAA                             AAAA           ",
                            "           AAAA                             AAAA           ",
                            "          BAAAABB            C            BBAAAAB          ",
                            "           AAAA                             AAAA           ",
                            "           AAAA                             AAAA           ",
                            "          CAAAACC                         CCAAAAC          ",
                            "        BBBBGBBBBBB                     BBBBBBGBBBB        ",
                            "                                                           ")
                    .slice("                                                           ",
                            "       BBBBGBBBBB                         BBBBBGBBBB       ",
                            "         CAAAAC                             CAAAAC         ",
                            "          AAAA                               AAAA          ",
                            "          AAAA                               AAAA          ",
                            "         BAAAAB                             BAAAAB         ",
                            "          AAAA                               AAAA          ",
                            "          AAAA                               AAAA          ",
                            "         CAAAAC                             CAAAAC         ",
                            "       BBBBGBBBBB                         BBBBBGBBBB       ",
                            "                                                           ")
                    .slice("                                                           ",
                            "      BBBBGBBBBB                           BBBBBGBBBB      ",
                            "        CAAACC                               CCAAAC        ",
                            "         AAA                                   AAA         ",
                            "         AAA                                   AAA         ",
                            "        BAAABB                               BBAAAB        ",
                            "         AAA                                   AAA         ",
                            "         AAA                                   AAA         ",
                            "        CAAACC                               CCAAAC        ",
                            "      BBBBGBBBBB                           BBBBBGBBBB      ",
                            "                                                           ")
                    .slice("                                                           ",
                            "     BBBBGBBBB                               BBBBGBBBB     ",
                            "       CAAAC                                   CAAAC       ",
                            "        AAA                                     AAA        ",
                            "        AAA                                     AAA        ",
                            "       BAAAB                                   BAAAB       ",
                            "        AAA                                     AAA        ",
                            "        AAA                                     AAA        ",
                            "       CAAAC                                   CAAAC       ",
                            "     BBBBGBBBB                               BBBBGBBBB     ",
                            "                                                           ")
                    .slice("                                                           ",
                            "     BBBGBBBB                                 BBBBGBBB     ",
                            "      CAAAAC                                   CAAAAC      ",
                            "       AAAA                                     AAAA       ",
                            "       AAAA                                     AAAA       ",
                            "      BAAAAB                                   BAAAAB      ",
                            "       AAAA                                     AAAA       ",
                            "       AAAA                                     AAAA       ",
                            "      CAAAAC                                   CAAAAC      ",
                            "     BBBGBBBB                                 BBBBGBBB     ",
                            "                                                           ")
                    .slice("                                                           ",
                            "    BBBGBBBB                                   BBBBGBBB    ",
                            "     CAAAAC                                     CAAAAC     ",
                            "      AAAA                                       AAAA      ",
                            "      AAAA                                       AAAA      ",
                            "     BAAAAB                                     BAAAAB     ",
                            "      AAAA                                       AAAA      ",
                            "      AAAA                                       AAAA      ",
                            "     CAAAAC                                     CAAAAC     ",
                            "    BBBGBBBB                                   BBBBGBBB    ",
                            "                                                           ")
                    .slice("                                                           ",
                            "    BBBGBBBB                                   BBBBGBBB    ",
                            "     CAAAC                                       CAAAC     ",
                            "      AAA                                         AAA      ",
                            "      AAA                                         AAA      ",
                            "     BAAAB                                       BAAAB     ",
                            "      AAA                                         AAA      ",
                            "      AAA                                         AAA      ",
                            "     CAAAC                                       CAAAC     ",
                            "    BBBGBBBB                                   BBBBGBBB    ",
                            "                                                           ")
                    .slice("                                                           ",
                            "   BBBGBBBB                                     BBBBGBBB   ",
                            "    CAAAAC                                       CAAAAC    ",
                            "     AAAA                                         AAAA     ",
                            "     AAAA                                         AAAA     ",
                            "    BAAAAB                                       BAAAAB    ",
                            "     AAAA                                         AAAA     ",
                            "     AAAA                                         AAAA     ",
                            "    CAAAAC                                       CAAAAC    ",
                            "   BBBGBBBB                                     BBBBGBBB   ",
                            "                                                           ")
                    .slice("                                                           ",
                            "   BBBGBBB                                       BBBGBBB   ",
                            "    CAAAC                                         CAAAC    ",
                            "     AAA                                           AAA     ",
                            "     AAA                                           AAA     ",
                            "    BAAAB                                         BAAAB    ",
                            "     AAA                                           AAA     ",
                            "     AAA                                           AAA     ",
                            "    CAAAC                                         CAAAC    ",
                            "   BBBGBBB                                       BBBGBBB   ",
                            "                                                           ")
                    .slice("                                                           ",
                            "  BBBGBBBB                                       BBBBGBBB  ",
                            "   CAAAC                                           CAAAC   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   BAAAB                                           BAAAB   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   CAAAC                                           CAAAC   ",
                            "  BBBGBBBB                                       BBBBGBBB  ",
                            "                                                           ")
                    .slice("                                                           ",
                            "  BBBGBBB                                         BBBGBBB  ",
                            "   CAAAC                                           CAAAC   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   BAAAB                                           BAAAB   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   CAAAC                                           CAAAC   ",
                            "  BBBGBBB                                         BBBGBBB  ",
                            "                                                           ")
                    .slice("                                                           ",
                            " BBBBGBBB                                         BBBGBBBB ",
                            "   CAAAC                                           CAAAC   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   BAAAB                                           BAAAB   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   CAAAC                                           CAAAC   ",
                            " BBBBGBBB                                         BBBGBBBB ",
                            "                                                           ")
                    .slice("                                                           ",
                            " BBBGBBB                                           BBBGBBB ",
                            "  CAAAC                                             CAAAC  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  BAAAB                                             BAAAB  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  CAAAC                                             CAAAC  ",
                            " BBBGBBB                                           BBBGBBB ",
                            "                                                           ")
                    .slice("                                                           ",
                            " BBBGBBB                                           BBBGBBB ",
                            "  CAAAC                                             CAAAC  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  BAAAB                                             BAAAB  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  CAAAC                                             CAAAC  ",
                            " BBBGBBB                                           BBBGBBB ",
                            "                                                           ")
                    .slice("                                                           ",
                            " BBBGBBB                                           BBBGBBB ",
                            "  CAAAC                                             CAAAC  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  BAAAB                                             BAAAB  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  CAAAC                                             CAAAC  ",
                            " BBBGBBB                                           BBBGBBB ",
                            "                                                           ")
                    .slice("                                                           ",
                            "BBBGBBBB                                           BBBBGBBB",
                            " CAAAC                                               CAAAC ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            " BAAAB                                               BAAAB ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            " CAAAC                                               CAAAC ",
                            "BBBGBBBB                                           BBBBGBBB",
                            "                                                           ")
                    .slice("                                                           ",
                            "BBBGBBB                                             BBBGBBB",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            "BBBGBBB                                             BBBGBBB",
                            "                                                           ")
                    .slice(" AAAAA                                               AAAAA ",
                            "BBBGBBB                                             BBBGBBB",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            "BBBGBBB                                             BBBGBBB",
                            " AAAAA                                               AAAAA ")
                    .slice("AAAAAAA                                             AAAAAAA",
                            "BBBGBBB                                             BBBGBBB",
                            " DAAAD                                               DAAAD ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            " DAAAD                                               DAAAD ",
                            "BBBGBBB                                             BBBGBBB",
                            "AAAAAAA                                             AAAAAAA")
                    .slice("AADDDAA                                             AADDDAA",
                            "BBBGBBB                                             BBBGBBB",
                            " DAAAD                                               DAAAD ",
                            "  AAA                                                 AAA  ",
                            "  AC                                                   CA  ",
                            "  ACCCC                                             CCCCA  ",
                            "  AC                                                   CA  ",
                            "  AAA                                                 AAA  ",
                            " DAAAD                                               DAAAD ",
                            "BBBGBBB                                             BBBGBBB",
                            "AADDDAA                                             AADDDAA")
                    .slice("AADFDAA                                             AADFDAA",
                            "BBBGBBB                                             BBBGBBB",
                            " DAAAD                                               DAAAD ",
                            "  AAA                                                 AAA  ",
                            "  ACCCC                                             CCCCA  ",
                            "  ACCCCCCC                                       CCCCCCCA  ",
                            "  ACCCC                                             CCCCA  ",
                            "  AAA                                                 AAA  ",
                            " DAAAD                                               DAAAD ",
                            "BBBGBBB                                             BBBGBBB",
                            "AADFDAA                                             AADFDAA")
                    .slice("AADDDAA                                             AADDDAA",
                            "BBBGBBB                                             BBBGBBB",
                            " DAAAD                                               DAAAD ",
                            "  AAA                                                 AAA  ",
                            "  AC                                                   CA  ",
                            "  ACCCC                                             CCCCA  ",
                            "  AC                                                   CA  ",
                            "  AAA                                                 AAA  ",
                            " DAAAD                                               DAAAD ",
                            "BBBGBBB                                             BBBGBBB",
                            "AADDDAA                                             AADDDAA")
                    .slice("AAAAAAA                                             AAAAAAA",
                            "BBBGBBB                                             BBBGBBB",
                            " DAAAD                                               DAAAD ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            " DAAAD                                               DAAAD ",
                            "BBBGBBB                                             BBBGBBB",
                            "AAAAAAA                                             AAAAAAA")
                    .slice(" AAAAA                                               AAAAA ",
                            "BBBGBBB                                             BBBGBBB",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            "BBBGBBB                                             BBBGBBB",
                            " AAAAA                                               AAAAA ")
                    .slice("                                                           ",
                            "BBBGBBB                                             BBBGBBB",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            " BAAAB                                               BAAAB ",
                            "BBBGBBB                                             BBBGBBB",
                            "                                                           ")
                    .slice("                                                           ",
                            "BBBGBBBB                                           BBBBGBBB",
                            " CAAAC                                               CAAAC ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            " BAAAB                                               BAAAB ",
                            "  AAA                                                 AAA  ",
                            "  AAA                                                 AAA  ",
                            " CAAAC                                               CAAAC ",
                            "BBBGBBBB                                           BBBBGBBB",
                            "                                                           ")
                    .slice("                                                           ",
                            " BBBGBBB                                           BBBGBBB ",
                            "  CAAAC                                             CAAAC  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  BAAAB                                             BAAAB  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  CAAAC                                             CAAAC  ",
                            " BBBGBBB                                           BBBGBBB ",
                            "                                                           ")
                    .slice("                                                           ",
                            " BBBGBBB                                           BBBGBBB ",
                            "  CAAAC                                             CAAAC  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  BAAAB                                             BAAAB  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  CAAAC                                             CAAAC  ",
                            " BBBGBBB                                           BBBGBBB ",
                            "                                                           ")
                    .slice("                                                           ",
                            " BBBGBBB                                           BBBGBBB ",
                            "  CAAAC                                             CAAAC  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  BAAAB                                             BAAAB  ",
                            "   AAA                                               AAA   ",
                            "   AAA                                               AAA   ",
                            "  CAAAC                                             CAAAC  ",
                            " BBBGBBB                                           BBBGBBB ",
                            "                                                           ")
                    .slice("                                                           ",
                            " BBBBGBBB                                         BBBGBBBB ",
                            "   CAAAC                                           CAAAC   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   BAAAB                                           BAAAB   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   CAAAC                                           CAAAC   ",
                            " BBBBGBBB                                         BBBGBBBB ",
                            "                                                           ")
                    .slice("                                                           ",
                            "  BBBGBBB                                         BBBGBBB  ",
                            "   CAAAC                                           CAAAC   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   BAAAB                                           BAAAB   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   CAAAC                                           CAAAC   ",
                            "  BBBGBBB                                         BBBGBBB  ",
                            "                                                           ")
                    .slice("                                                           ",
                            "  BBBGBBBB                                       BBBBGBBB  ",
                            "   CAAAC                                           CAAAC   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   BAAAB                                           BAAAB   ",
                            "    AAA                                             AAA    ",
                            "    AAA                                             AAA    ",
                            "   CAAAC                                           CAAAC   ",
                            "  BBBGBBBB                                       BBBBGBBB  ",
                            "                                                           ")
                    .slice("                                                           ",
                            "   BBBGBBB                                       BBBGBBB   ",
                            "    CAAAC                                         CAAAC    ",
                            "     AAA                                           AAA     ",
                            "     AAA                                           AAA     ",
                            "    BAAAB                                         BAAAB    ",
                            "     AAA                                           AAA     ",
                            "     AAA                                           AAA     ",
                            "    CAAAC                                         CAAAC    ",
                            "   BBBGBBB                                       BBBGBBB   ",
                            "                                                           ")
                    .slice("                                                           ",
                            "   BBBGBBBB                                     BBBBGBBB   ",
                            "    CAAAAC                                       CAAAAC    ",
                            "     AAAA                                         AAAA     ",
                            "     AAAA                                         AAAA     ",
                            "    BAAAAB                                       BAAAAB    ",
                            "     AAAA                                         AAAA     ",
                            "     AAAA                                         AAAA     ",
                            "    CAAAAC                                       CAAAAC    ",
                            "   BBBGBBBB                                     BBBBGBBB   ",
                            "                                                           ")
                    .slice("                                                           ",
                            "    BBBGBBBB                                   BBBBGBBB    ",
                            "     CAAAC                                       CAAAC     ",
                            "      AAA                                         AAA      ",
                            "      AAA                                         AAA      ",
                            "     BAAAB                                       BAAAB     ",
                            "      AAA                                         AAA      ",
                            "      AAA                                         AAA      ",
                            "     CAAAC                                       CAAAC     ",
                            "    BBBGBBBB                                   BBBBGBBB    ",
                            "                                                           ")
                    .slice("                                                           ",
                            "    BBBGBBBB                                   BBBBGBBB    ",
                            "     CAAAAC                                     CAAAAC     ",
                            "      AAAA                                       AAAA      ",
                            "      AAAA                                       AAAA      ",
                            "     BAAAAB                                     BAAAAB     ",
                            "      AAAA                                       AAAA      ",
                            "      AAAA                                       AAAA      ",
                            "     CAAAAC                                     CAAAAC     ",
                            "    BBBGBBBB                                   BBBBGBBB    ",
                            "                                                           ")
                    .slice("                                                           ",
                            "     BBBGBBBB                                 BBBBGBBB     ",
                            "      CAAAAC                                   CAAAAC      ",
                            "       AAAA                                     AAAA       ",
                            "       AAAA                                     AAAA       ",
                            "      BAAAAB                                   BAAAAB      ",
                            "       AAAA                                     AAAA       ",
                            "       AAAA                                     AAAA       ",
                            "      CAAAAC                                   CAAAAC      ",
                            "     BBBGBBBB                                 BBBBGBBB     ",
                            "                                                           ")
                    .slice("                                                           ",
                            "     BBBBGBBBB                               BBBBGBBBB     ",
                            "       CAAAC                                   CAAAC       ",
                            "        AAA                                     AAA        ",
                            "        AAA                                     AAA        ",
                            "       BAAAB                                   BAAAB       ",
                            "        AAA                                     AAA        ",
                            "        AAA                                     AAA        ",
                            "       CAAAC                                   CAAAC       ",
                            "     BBBBGBBBB                               BBBBGBBBB     ",
                            "                                                           ")
                    .slice("                                                           ",
                            "      BBBBGBBBBB                           BBBBBGBBBB      ",
                            "        CAAACC                               CCAAAC        ",
                            "         AAA                                   AAA         ",
                            "         AAA                                   AAA         ",
                            "        BAAABB                               BBAAAB        ",
                            "         AAA                                   AAA         ",
                            "         AAA                                   AAA         ",
                            "        CAAACC                               CCAAAC        ",
                            "      BBBBGBBBBB                           BBBBBGBBBB      ",
                            "                                                           ")
                    .slice("                                                           ",
                            "       BBBBGBBBBB                         BBBBBGBBBB       ",
                            "         CAAAAC                             CAAAAC         ",
                            "          AAAA                               AAAA          ",
                            "          AAAA                               AAAA          ",
                            "         BAAAAB                             BAAAAB         ",
                            "          AAAA                               AAAA          ",
                            "          AAAA                               AAAA          ",
                            "         CAAAAC                             CAAAAC         ",
                            "       BBBBGBBBBB                         BBBBBGBBBB       ",
                            "                                                           ")
                    .slice("                                                           ",
                            "        BBBBGBBBBBB                     BBBBBBGBBBB        ",
                            "          CAAAACC                         CCAAAAC          ",
                            "           AAAA                             AAAA           ",
                            "           AAAA                             AAAA           ",
                            "          BAAAABB            C            BBAAAAB          ",
                            "           AAAA                             AAAA           ",
                            "           AAAA                             AAAA           ",
                            "          CAAAACC                         CCAAAAC          ",
                            "        BBBBGBBBBBB                     BBBBBBGBBBB        ",
                            "                                                           ")
                    .slice("                                                           ",
                            "         BBBBGBBBBBBB                 BBBBBBBGBBBB         ",
                            "           CAAAAAC                       CAAAAAC           ",
                            "            AAAAA                         AAAAA            ",
                            "            AAAAA                         AAAAA            ",
                            "           BAAAAAB           C           BAAAAAB           ",
                            "            AAAAA                         AAAAA            ",
                            "            AAAAA                         AAAAA            ",
                            "           CAAAAAC                       CAAAAAC           ",
                            "         BBBBGBBBBBBB                 BBBBBBBGBBBB         ",
                            "                                                           ")
                    .slice("                                                           ",
                            "          BBBBGGBBBBBBBBB         BBBBBBBBBGGBBBB          ",
                            "            CAAAAACCC                 CCCAAAAAC            ",
                            "             AAAAA                       AAAAA             ",
                            "             AAAAA                       AAAAA             ",
                            "            BAAAAABBB        C        BBBAAAAAB            ",
                            "             AAAAA                       AAAAA             ",
                            "             AAAAA                       AAAAA             ",
                            "            CAAAAACCC                 CCCAAAAAC            ",
                            "          BBBBGGBBBBBBBBB         BBBBBBBBBGGBBBB          ",
                            "                                                           ")
                    .slice("                           AAAAA                           ",
                            "           BBBBBGGBBBBBBBBBBBBBBBBBBBBBBBGGBBBBB           ",
                            "             CAAAAAAACCC           CCCAAAAAAAC             ",
                            "              AAAAAAA                 AAAAAAA              ",
                            "              AAAAAAA        C        AAAAAAA              ",
                            "             BAAAAAAABBB    CCC    BBBAAAAAAAB             ",
                            "              AAAAAAA        C        AAAAAAA              ",
                            "              AAAAAAA                 AAAAAAA              ",
                            "             CAAAAAAACCC           CCCAAAAAAAC             ",
                            "           BBBBBGGBBBBBBBBBBBBBBBBBBBBBBBGGBBBBB           ",
                            "                           AAAAA                           ")
                    .slice("                          AAAAAAA                          ",
                            "            BBBBBBGGGBBBBBBBBBBBBBBBBBGGGBBBBBB            ",
                            "              CCAAAAAAAACBBDDDDDBBCAAAAAAAACC              ",
                            "                AAAAAAAA BB     BB AAAAAAAA                ",
                            "                AAAAAAAA BB  C  BB AAAAAAAA                ",
                            "              BBAAAAAAAABBB CCC BBBAAAAAAAABB              ",
                            "                AAAAAAAA BB  C  BB AAAAAAAA                ",
                            "                AAAAAAAA BB     BB AAAAAAAA                ",
                            "              CCAAAAAAAACBBDDDDDBBCAAAAAAAACC              ",
                            "            BBBBBBGGGBBBBBBBBBBBBBBBBBGGGBBBBBB            ",
                            "                          AAAAAAA                          ")
                    .slice("                          AADDDAA                          ",
                            "              BBBBBBBGGGBBBBBBBBBBBGGGBBBBBBB              ",
                            "                CCAAAAAAAAAAAAAAAAAAAAAAACC                ",
                            "                  AAAAAAAAAAAAAAAAAAAAAAA                  ",
                            "                  AAAAAAAAAA C AAAAAAAAAA                  ",
                            "                BBAAAAAAAAAACCCAAAAAAAAAABB                ",
                            "                  AAAAAAAAAA C AAAAAAAAAA                  ",
                            "                  AAAAAAAAAAAAAAAAAAAAAAA                  ",
                            "                CCAAAAAAAAAAAAAAAAAAAAAAACC                ",
                            "              BBBBBBBGGGBBBBBBBBBBBGGGBBBBBBB              ",
                            "                          AADDDAA                          ")
                    .slice("                          AADFDAA                          ",
                            "                BBBBBBBBGGGGGGGGGGGBBBBBBBB                ",
                            "                  CCCAAAAAAAAAAAAAAAAACCC                  ",
                            "                     AAAAAAAAAAAAAAAAA                     ",
                            "                     AAAAAAACCCAAAAAAA                     ",
                            "                  BBBAAAAAAACCCAAAAAAABBB                  ",
                            "                     AAAAAAACCCAAAAAAA                     ",
                            "                     AAAAAAAAAAAAAAAAA                     ",
                            "                  CCCAAAAAAAAAAAAAAAAACCC                  ",
                            "                BBBBBBBBGGGGGGGGGGGBBBBBBBB                ",
                            "                          AADFDAA                          ")
                    .slice("                          AADDDAA                          ",
                            "                  BBBBBBBBBBBBBBBBBBBBBBB                  ",
                            "                     CCCAAAAAAAAAAACCC                     ",
                            "                        AAAAAAAAAAA                        ",
                            "                        AAAAAAAAAAA                        ",
                            "                     BBBAAAAAAAAAAABBB                     ",
                            "                        AAAAAAAAAAA                        ",
                            "                        AAAAAAAAAAA                        ",
                            "                     CCCAAAAAAAAAAACCC                     ",
                            "                  BBBBBBBBBBBBBBBBBBBBBBB                  ",
                            "                          AADDDAA                          ")
                    .slice("                          AAAAAAA                          ",
                            "                    BBBBBBBBBBBBBBBBBBB                    ",
                            "                        CBBDDDDDBBC                        ",
                            "                         BB  B  BB                         ",
                            "                         BB B B BB                         ",
                            "                        BBBB Q BBBB                        ",
                            "                         BB B B BB                         ",
                            "                         BB  B  BB                         ",
                            "                        CBBDDDDDBBC                        ",
                            "                    BBBBBBBBBBBBBBBBBBB                    ",
                            "                          AAAAAAA                          ")
                    .slice("                           AAAAA                           ",
                            "                        BBBBBBBBBBB                        ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                                                           ",
                            "                        BBBBBBBBBBB                        ",
                            "                           AAAAA                           ")
                    .where(' ', any())
                    .where('Q', controller(blocks(definition.getBlock())))
                    .where('A', blocks(CASING_HIGH_TEMPERATURE_SMELTING.get()))
                    .where('B', blocks(MULTIPURPOSE_INTERSTELLAR_GRADE_CASING.get()))
                    .where('C', blocks(MULTIPURPOSE_INTERSTELLAR_GRADE_CASING.get()))
                    .where('D', blocks(CASING_ATOMIC.get()))
                    .where('E', blocks(ULTRA_POWERED_CASING.get()))
                    .where('F', blocks(CYCLOZINE_CHEMICALLY_REPELLING_CASING.get())
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                            .or(Predicates.abilities(PartAbility.INPUT_LASER).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.OUTPUT_LASER).setMaxGlobalLimited(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16)))
                    .where('G', blocks(CASING_HIGH_TEMPERATURE_SMELTING.get()))
                    .build())
            .model(createWorkableCasingMachineModel(
                    CosmicCore.id("block/casings/solid/vomahine_certified_chemically_resistant_casing"),
                    GTCEu.id("block/multiblock/fusion_reactor"))
                    .andThen(model -> model.addDynamicRenderer(CosmicDynamicRenderHelpers::getStarBallastRender)))
            .hasBER(true)
            .tooltips(Component.translatable("cosmiccore.multiblock.iris.tooltip.0"),
                    Component.translatable("cosmiccore.multiblock.iris.tooltip.1"),
                    Component.translatable("cosmiccore.multiblock.iris.tooltip.2"),
                    Component.translatable("cosmiccore.multiblock.iris.tooltip.3"))
            .register();

    public static void init() {}
}
