package com.ghostipedia.cosmiccore.common.machine.multiblock.multi;

import com.ghostipedia.cosmiccore.CosmicCore;
import com.ghostipedia.cosmiccore.common.data.recipe.CosmicRecipeModifiers;
import com.ghostipedia.cosmiccore.common.machine.multiblock.multi.logic.TitanFusionReactorMachine;
import com.ghostipedia.cosmiccore.gtbridge.CosmicRecipeTypes;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.multiblock.pattern.MultiblockPatternBuilder;
import com.gregtechceu.gtceu.api.recipe.OverclockingLogic;
import com.gregtechceu.gtceu.common.data.GTBlocks;
import com.gregtechceu.gtceu.common.data.GTMaterials;
import com.gregtechceu.gtceu.common.data.GTRecipeModifiers;

import static com.ghostipedia.cosmiccore.api.registries.CosmicRegistration.REGISTRATE;
import static com.ghostipedia.cosmiccore.common.data.CosmicBlocks.*;
import static com.gregtechceu.gtceu.api.multiblock.Predicates.*;
import static com.gregtechceu.gtceu.api.multiblock.Predicates.blocks;

public class TitanFusion {

    public final static MultiblockMachineDefinition TITAN_FUSION_REACTOR = REGISTRATE
            .multiblock("titan_fusion_reactor",
                    TitanFusionReactorMachine::new)
            .langValue("§9Titan Fusion Reactor")
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType(CosmicRecipeTypes.TITAN_FUSION_RECIPES)
            .appearanceBlock(OSCILLATING_GILDED_PTHANTERUM_CASING)
            .partAppearance((controller, part, side) -> OSCILLATING_GILDED_PTHANTERUM_CASING.getDefaultState())
            .recipeModifiers(CosmicRecipeModifiers::titanReactorParallel,
                    GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK),
                    GTRecipeModifiers.BATCH_MODE)
            // spotless:off
            .pattern(definition -> MultiblockPatternBuilder.start()
                    .slice("         AAAAA         ", "         AAAAA         ", "         AAAAA         ", "         AAAAA         ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "          AAA          ", "         AAAAA         ", "         AAAAA         ", "         AAAAA         ", "          AAA          ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "         AAAAA         ", "         AAAAA         ", "         AAAAA         ", "         AAAAA         ")
                    .slice("        BBBBBBB        ", "        BBBBBBB        ", "        BBBBBBB        ", "         AACAA         ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "       AA  C  AA       ", "      AAA  C  AAA      ", "       AA  C  AA       ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "         AACAA         ", "        BBBBBBB        ", "        BBBBBBB        ", "        BBBBBBB        ")
                    .slice("      BBBBBBBBBBB      ", "      BBBBBBBBBBB      ", "      BBBBBBBBBBB      ", "        CAAAAAC        ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "     A           A     ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "        CAAAAAC        ", "      BBBBBBBBBBB      ", "      BBBBBBBBBBB      ", "      BBBBBBBBBBB      ")
                    .slice("     BBBBBBBBBBBBB     ", "     BBBBBBBBBBBBB     ", "     BBBBBBBBBBBBB     ", "      CC ACACA CC      ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "   AA     C C     AA   ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "      CC ACACA CC      ", "     BBBBBBBBBBBBB     ", "     BBBBBBBBBBBBB     ", "     BBBBBBBBBBBBB     ")
                    .slice("    BBBBBBBBBBBBBBB    ", "    BBBBBBBBBBBBBBB    ", "    BBBBBBBBBBBBBBB    ", "     C     DDD   C     ", "          DDDD         ", "         DDDD          ", "         DDD           ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "           EEE         ", "   A      EEEE     A   ", "         EEEE          ", "         EEE           ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "           DDD         ", "          DDDD         ", "     C   DDDD    C     ", "    BBBBBBBBBBBBBBB    ", "    BBBBBBBBBBBBBBB    ", "    BBBBBBBBBBBBBBB    ")
                    .slice("   BBBBBBBBBBBBBBBBB   ", "   BBBBBBBBBBBBBBBBB   ", "   BBBBBBBBBBBBBBBBB   ", "    C     DD  DD  C    ", "         D    D        ", "        D    D         ", "       DD  DD          ", "       DDDD            ", "                       ", "                       ", "                       ", "                       ", "            EEEE       ", "          EE  EE       ", "  A      E    E     A  ", "        E    E         ", "       EE  EE          ", "       EEEE            ", "                       ", "                       ", "                       ", "                       ", "            DDDD       ", "          DD  DD       ", "         D    D        ", "    C   D    D    C    ", "   BBBBBBBBBBBBBBBBB   ", "   BBBBBBBBBBBBBBBBB   ", "   BBBBBBBBBBBBBBBBB   ")
                    .slice("  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "   C      DD    D  C   ", "         D    DD       ", "       DD    D         ", "      D    DD          ", "      D  DD            ", "      DDD              ", "                       ", "                       ", "              EEE      ", "            EE  E      ", "          EE    E      ", " A       E    EE     A ", "       EE    E         ", "      E    EE          ", "      E  EE            ", "      EEE              ", "                       ", "                       ", "              DDD      ", "            DD  D      ", "          DD    D      ", "         D    DD       ", "   C   DD    D     C   ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ")
                    .slice("  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "   C       D    D  C   ", "         DD   DD       ", "       DD   DD         ", "      D    D           ", "     D    D            ", "     D  DD             ", "      DD               ", "               EE      ", "             EE  E     ", "            E    E     ", " A         E    E    A ", " A       EE   EE     A ", " A     EE   EE       A ", "      E    E           ", "     E    E            ", "     E  EE             ", "      EE               ", "               DD      ", "             DD  D     ", "            D    D     ", "           D    D      ", "         DD   DD       ", "   C   DD   DD     C   ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ")
                    .slice(" BBBBBBBBBBBBBBBBBBBBB ", " BBBBBBBBBBBBBBBBBBBBB ", " BBBBBBBBBBBBBBBBBBBBB ", "  C        DD  DD   C  ", "          DDDDD        ", "        DDDDD          ", "      DD  DD           ", "     D    D            ", "     D   D             ", "     DDDD              ", "              EEEE     ", "             E   E     ", "            E    E     ", " A         EE  EE    A ", " A        EEEEE      A ", " A      EEEEE        A ", "      EE  EE           ", "     E    E            ", "     E   E             ", "     EEEE              ", "              DDDD     ", "             D   D     ", "            D    D     ", "           DD  DD      ", "          DDDDD        ", "  C     DDDDD       C  ", " BBBBBBBBBBBBBBBBBBBBB ", " BBBBBBBBBBBBBBBBBBBBB ", " BBBBBBBBBBBBBBBBBBBBB ")
                    .slice("ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "AAAA      FFFDDD   AAAA", "          FFF          ", "          FFF          ", "       DDDFFF          ", "     DD  DFFF          ", "    D    DFFF          ", "    D   D FFF  EEE     ", "     DDD  FFF E   E    ", "          FFFE    E    ", "          FFFE  EE     ", "A         FFFEEE      A", "A         FFF         A", "A         FFF         A", "       EEEFFF          ", "     EE  EFFF          ", "    E    EFFF          ", "    E   E FFF  DDD     ", "     EEE  FFF D   D    ", "          FFFD    D    ", "          FFFD  DD     ", "          FFFDDD       ", "          FFF          ", "AAAA      FFF      AAAA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA")
                    .slice("ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "AAAC     FG GF     CAAA", "   C     FG GF     C   ", "   C     FG GF     C   ", "   C     FG GF     C   ", "   C DDDDFG GF     C   ", "   CD   DFG GF  EE C   ", "   CD   DFG GFEE  EC   ", "   CD  DDFG GFE   EC   ", "   C DD  FG GFE   EC   ", "A  C     FG GFEEEE C  A", "A  C     FG GF     C  A", "A  C     FG GF     C  A", "A  C     FG GF     C  A", "A  C     FG GF     C  A", "   C EEEEFG GF     C   ", "   CE   EFG GF  DD C   ", "   CE   EFG GFDD  DC   ", "   CE  EEFG GFD   DC   ", "   C EE  FG GFD   DC   ", "   C     FG GFDDDD C   ", "   C     FG GF     C   ", "   C     FG GF     C   ", "AAAC     FG GF     CAAA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA")
                    .slice("ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ACAA     F   F     AACA", " C       F   F       C ", " C       F   F       C ", " C       F   F       C ", " C       F   F       C ", " C  DDDDDF   FEEEEE  C ", " C  D   DF   FE   E  C ", " C  D   DF   FE   E  C ", " C  DDDDDF   FEEEEE  C ", "AC       F   F       CA", "AC       F   F       CA", "AC       F   F       CA", "AC       F   F       CA", "AC       F   F       CA", " C       F   F       C ", " C  EEEEEF   FDDDDD  C ", " C  E   EF   FD   D  C ", " C  E   EF   FD   D  C ", " C  EEEEEF   FDDDDD  C ", " C       F   F       C ", " C       F   F       C ", " C       F   F       C ", "ACAA     F   F     AAAA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA")
                    .slice("ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "AAAC     FG GF     CAAA", "   C     FG GF     C   ", "   C     FG GF     C   ", "   C     FG GF     C   ", "   C     FG GFEEEE C   ", "   C DD  FG GFE   EC   ", "   CD  DDFG GFE   EC   ", "   CD   DFG GFEE  EC   ", "   CD   DFG GF  EE C   ", "A  C DDDDFG GF     C  A", "A  C     FG GF     C  A", "A  C     FG GF     C  A", "A  C     FG GF     C  A", "A  C     FG GF     C  A", "   C     FG GFDDDD C   ", "   C EE  FG GFD   DC   ", "   CE  EEFG GFD   DC   ", "   CE   EFG GFDD  DC   ", "   CE   EFG GF  DD C   ", "   C EEEEFG GF     C   ", "   C     FG GF     C   ", "   C     FG GF     C   ", "AAAC     FG GF     CAAA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA")
                    .slice("ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "AAAA   EEEFFF      AAAA", "          FFF          ", "          FFF          ", "          FFFEEE       ", "          FFFE  EE     ", "          FFFE    E    ", "     DDD  FFF E   E    ", "    D   D FFF  EEE     ", "    D    DFFF          ", "     DD  DFFF          ", "A      DDDFFF         A", "A         FFF         A", "A         FFF         A", "          FFFDDD       ", "          FFFD  DD     ", "          FFFD    D    ", "     EEE  FFF D   D    ", "    E   E FFF  DDD     ", "    E    EFFF          ", "     EE  EFFF          ", "       EEEFFF          ", "          FFF          ", "AAAA      FFF      AAAA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA", "ABBBBBBBBBBBBBBBBBBBBBA")
                    .slice(" BBBBBBBBBBBBBBBBBBBBB ", " BBBBBBBBBBBBBBBBBBBBB ", " BBBBBBBBBBBBBBBBBBBBB ", "  C   EE  EE        C  ", "        EEEEE          ", "          EEEEE        ", "           EE  EE      ", "            E    E     ", "             E   E     ", "              EEEE     ", "     DDDD              ", "     D   D             ", "     D    D            ", " A    DD  DD         A ", " A      DDDDD        A ", " A        DDDDD      A ", "           DD  DD      ", "            D    D     ", "             D   D     ", "              DDDD     ", "     EEEE              ", "     E   E             ", "     E    E            ", "      EE  EE           ", "        EEEEE          ", "  C       EEEEE     C  ", " BBBBBBBBBBBBBBBBBBBBB ", " BBBBBBBBBBBBBBBBBBBBB ", " BBBBBBBBBBBBBBBBBBBBB ")
                    .slice("  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "   C  E    E       C   ", "       EE   EE         ", "         EE   EE       ", "           E    E      ", "            E    E     ", "             EE  E     ", "               EE      ", "      DD               ", "     D  DD             ", "     D    D            ", " A    D    D         A ", " A     DD   DD       A ", " A       DD   DD     A ", "           D    D      ", "            D    D     ", "             DD  D     ", "               DD      ", "      EE               ", "     E  EE             ", "     E    E            ", "      E    E           ", "       EE   EE         ", "   C     EE   EE   C   ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ")
                    .slice("  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "   C  E    EE      C   ", "       EE    E         ", "         E    EE       ", "          EE    E      ", "            EE  E      ", "              EEE      ", "                       ", "                       ", "      DDD              ", "      D  DD            ", "      D    DD          ", " A     DD    D       A ", "         D    DD       ", "          DD    D      ", "            DD  D      ", "              DDD      ", "                       ", "                       ", "      EEE              ", "      E  EE            ", "      E    EE          ", "       EE    E         ", "   C     E    EE   C   ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ", "  BBBBBBBBBBBBBBBBBBB  ")
                    .slice("   BBBBBBBBBBBBBBBBB   ", "   BBBBBBBBBBBBBBBBB   ", "   BBBBBBBBBBBBBBBBB   ", "    C  EE  EE     C    ", "        E    E         ", "         E    E        ", "          EE  EE       ", "            EEEE       ", "                       ", "                       ", "                       ", "                       ", "       DDDD            ", "       DD  DD          ", "  A     D    D      A  ", "         D    D        ", "          DD  DD       ", "            DDDD       ", "                       ", "                       ", "                       ", "                       ", "       EEEE            ", "       EE  EE          ", "        E    E         ", "    C    E    E   C    ", "   BBBBBBBBBBBBBBBBB   ", "   BBBBBBBBBBBBBBBBB   ", "   BBBBBBBBBBBBBBBBB   ")
                    .slice("    BBBBBBBBBBBBBBB    ", "    BBBBBBBBBBBBBBB    ", "    BBBBBBBBBBBBBBB    ", "     C   EEE     C     ", "         EEEE          ", "          EEEE         ", "           EEE         ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "         DDD           ", "   A     DDDD      A   ", "          DDDD         ", "           DDD         ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "         EEE           ", "         EEEE          ", "     C    EEEE   C     ", "    BBBBBBBBBBBBBBB    ", "    BBBBBBBBBBBBBBB    ", "    BBBBBBBBBBBBBBB    ")
                    .slice("     BBBBBBBBBBBBB     ", "     BBBBBBBBBBBBB     ", "     BBBBBBBBBBBBB     ", "      CC ACACA CC      ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "   AA     C C     AA   ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "          C C          ", "      CC ACACA CC      ", "     BBBBBBBBBBBBB     ", "     BBBBBBBBBBBBB     ", "     BBBBBBBBBBBBB     ")
                    .slice("      BBBBBBBBBBB      ", "      BBBBBBBBBBB      ", "      BBBBBBBBBBB      ", "        CAAAAAC        ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "     A           A     ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "        CAAAAAC        ", "      BBBBBBBBBBB      ", "      BBBBBBBBBBB      ", "      BBBBBBBBBBB      ")
                    .slice("        BBBBBBB        ", "        BBBBBBB        ", "        BBBBBBB        ", "         AACAA         ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "       AA  C  AA       ", "      AAA  C  AAA      ", "       AA  C  AA       ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "           C           ", "         AACAA         ", "        BBBBBBB        ", "        BBBBBBB        ", "        BBBBBBB        ")
                    .slice("         AAAAA         ", "         AAAAA         ", "         AAAAA         ", "         AAAAA         ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "          AAA          ", "         AAAAA         ", "         AAQAA         ", "         AAAAA         ", "          AAA          ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "                       ", "         AAAAA         ", "         AAAAA         ", "         AAAAA         ", "         AAAAA         ")

                    .where(' ', any())
                    .where('Q', controller(blocks(definition.getBlock())))
                    .where('A', blocks(OSCILLATING_GILDED_PTHANTERUM_CASING.get())
                            .or(autoAbilities())
                            .or(autoAbilities(CosmicRecipeTypes.TITAN_FUSION_RECIPES))
                            .or(abilities(PartAbility.IMPORT_FLUIDS,PartAbility.IMPORT_FLUIDS_4X,PartAbility.IMPORT_FLUIDS_9X))
                            .or(abilities(PartAbility.EXPORT_ITEMS,PartAbility.EXPORT_FLUIDS))
                            .or(abilities(PartAbility.INPUT_ENERGY,PartAbility.INPUT_LASER).setExactLimit(1))
                            .or(abilities(PartAbility.MAINTENANCE).setExactLimit(1))) //Part IO go here
                    .where('B', blocks(BICHROMAL_NEVRAMITE_CASING.get()))
                    .where('C', frames(GTMaterials.Neutronium))
                    .where('D', blocks(GTBlocks.FUSION_CASING_MK2.get()))
                    .where('F',  blocks(ZBLAN_REINFORCED_GLASS.get()))
                    .where('E', blocks(GTBlocks.FUSION_CASING_MK3.get()))
                    .where('G', blocks(GTBlocks.FUSION_COIL.get()))
                    .build())
            // spotless:on
            .workableCasingModel(CosmicCore.id("block/casings/solid/oscillating_gilded_pthanterum_casings"),
                    GTCEu.id("block/multiblock/fusion_reactor"))
            .register();

    public static void init() {}
}
